package com.recharge.model;
// Generated Aug 31, 2017 9:56:23 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Api generated by hbm2java
 */


@Entity
@Table(name = "api")
@NamedQueries({
	@NamedQuery(name="getApibynameandurl",query="From Api where apiName=:apiName and url=:url"),
	@NamedQuery(name="getApibyapiId",query="From Api where apiId=:apiId")
})
public class Api  implements java.io.Serializable {


     private Integer apiId;
     private String apiName;
     private String username;
     private String password;
     private String url;

    public Api() {
    }
    
    

    public Api(String apiName, String url) {
		super();
		this.apiName = apiName;
		this.url = url;
	}
    
    
    
    
	public Api(Integer apiId, String apiName, String username, String password, String url) {
		super();
		this.apiId = apiId;
		this.apiName = apiName;
		this.username = username;
		this.password = password;
		this.url = url;
	}



	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Api(String apiName) {
       this.apiName = apiName;
    }
    @Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    public Integer getApiId() {
        return this.apiId;
    }
    
    public void setApiId(Integer apiId) {
        this.apiId = apiId;
    }
    public String getApiName() {
        return this.apiName;
    }
    
    public void setApiName(String apiName) {
        this.apiName = apiName;
    }



	public String getUsername() {
		return username;
	}



	public void setUsername(String username) {
		this.username = username;
	}



	public String getPassword() {
		return password;
	}



	public void setPassword(String password) {
		this.password = password;
	}




}


