package com.recharge.model;
// Generated Oct 18, 2017 10:15:47 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Apisetting generated by hbm2java
 */

@Entity
@Table(name = "apisetting")

@NamedQueries({ 
	@NamedQuery(name = "getApisettingByuserId", query = "from Apisetting As apiset where apiset.userId= :userId"),
})
public class Apisetting implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String responseUrl;
	private String ip;
	private String date;
	private String time;

	public Apisetting() {
	}

	public Apisetting(String userId, String responseUrl, String ip, String date, String time) {
		this.userId = userId;
		this.responseUrl = responseUrl;
		this.ip = ip;
		this.date = date;
		this.time = time;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
	@Column(name = "response_url")
	public String getResponseUrl() {
		return this.responseUrl;
	}

	public void setResponseUrl(String responseUrl) {
		this.responseUrl = responseUrl;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

}
