package com.recharge.model;
// Generated Oct 18, 2017 10:15:47 AM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Apitrace generated by hbm2java
 */



@Entity
@Table(name = "apitrace")


public class Apitrace implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String transId;
	private String url;
	private String response;
	private String date;
	private String time;

	public Apitrace() {
	}

	public Apitrace(String userId, String transId, String url, String response, String date, String time) {
		this.userId = userId;
		this.transId = transId;
		this.url = url;
		this.response = response;
		this.date = date;
		this.time = time;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getTransId() {
		return this.transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getResponse() {
		return this.response;
	}

	public void setResponse(String response) {
		this.response = response;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

}
