package com.recharge.model;
// Generated Aug 31, 2017 9:56:23 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Balancetransafer generated by hbm2java
 */

@Entity
@Table(name = "balancetransafer")
public class Balancetransafer  implements java.io.Serializable {


     private Integer transferId;
     private String fromId;
     private Double fromOpenBal;
     private Double transferAmount;
     private Double fromClosingBal;
     private String toId;
     private Double toOpenBal;
     private Double recievedAmount;
     private Double toclosingBal;
     private String remarks;
     private String narration;
     private String date;
     private String time;
     private String wlId;

    public Balancetransafer() {
    }

    public Balancetransafer(String fromId, Double fromOpenBal, Double transferAmount, Double fromClosingBal, String toId, Double toOpenBal, Double recievedAmount, Double toclosingBal, String remarks, String narration, String date, String time, String wlId) {
       this.fromId = fromId;
       this.fromOpenBal = fromOpenBal;
       this.transferAmount = transferAmount;
       this.fromClosingBal = fromClosingBal;
       this.toId = toId;
       this.toOpenBal = toOpenBal;
       this.recievedAmount = recievedAmount;
       this.toclosingBal = toclosingBal;
       this.remarks = remarks;
       this.narration = narration;
       this.date = date;
       this.time = time;
       this.wlId = wlId;
    }
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Integer getTransferId() {
        return this.transferId;
    }
    
    public void setTransferId(Integer transferId) {
        this.transferId = transferId;
    }
    public String getFromId() {
        return this.fromId;
    }
    
    public void setFromId(String fromId) {
        this.fromId = fromId;
    }
    public Double getFromOpenBal() {
        return this.fromOpenBal;
    }
    
    public void setFromOpenBal(Double fromOpenBal) {
        this.fromOpenBal = fromOpenBal;
    }
    public Double getTransferAmount() {
        return this.transferAmount;
    }
    
    public void setTransferAmount(Double transferAmount) {
        this.transferAmount = transferAmount;
    }
    public Double getFromClosingBal() {
        return this.fromClosingBal;
    }
    
    public void setFromClosingBal(Double fromClosingBal) {
        this.fromClosingBal = fromClosingBal;
    }
    public String getToId() {
        return this.toId;
    }
    
    public void setToId(String toId) {
        this.toId = toId;
    }
    public Double getToOpenBal() {
        return this.toOpenBal;
    }
    
    public void setToOpenBal(Double toOpenBal) {
        this.toOpenBal = toOpenBal;
    }
    public Double getRecievedAmount() {
        return this.recievedAmount;
    }
    
    public void setRecievedAmount(Double recievedAmount) {
        this.recievedAmount = recievedAmount;
    }
    public Double getToclosingBal() {
        return this.toclosingBal;
    }
    
    public void setToclosingBal(Double toclosingBal) {
        this.toclosingBal = toclosingBal;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getNarration() {
        return this.narration;
    }
    
    public void setNarration(String narration) {
        this.narration = narration;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    
    @Column(name = "wl_id")
    public String getWlId() {
        return this.wlId;
    }
    
    public void setWlId(String wlId) {
        this.wlId = wlId;
    }




}


