package com.recharge.model;
// Generated Oct 6, 2017 10:45:57 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Bankdetails generated by hbm2java
 */

@Entity
@Table(name = "bankdetails")

@NamedQueries({ @NamedQuery(name = "GetBankDetailsByWlId", query = "from Bankdetails As bd where bd.wlId=:wlId") })
public class Bankdetails implements java.io.Serializable {

	private Integer id;
	private String accName;
	private String accNo;
	private String ifscCode;
	private String branchName;
	private String bankName;
	private String wlId;
	private String date;
	private String time;

	public Bankdetails() {
	}

	public Bankdetails(String accName, String accNo, String ifscCode, String branchName, String bankName, String wlId,
			String date, String time) {
		this.accName = accName;
		this.accNo = accNo;
		this.ifscCode = ifscCode;
		this.branchName = branchName;
		this.bankName = bankName;
		this.wlId = wlId;
		this.date = date;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	public String getAccNo() {
		return this.accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}

	public String getIfscCode() {
		return this.ifscCode;
	}

	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "wl_id")
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

}
