package com.recharge.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

// Generated Nov 3, 2017 11:11:33 AM by Hibernate Tools 4.3.1

/**
 * Complain generated by hbm2java
 */

@Entity
@Table(name = "complain")

@NamedQueries({
	@NamedQuery(name = "getComplainBySubject", query = "from Complain As c where c.subject=:subject")
})
public class Complain implements java.io.Serializable {

	private Integer id;
	private String subject;
	private String userId;
	private String complain;
	private String status;
	private String adminMessage;
	private String wlId;
	private String complainType;
	private String date;
	private String time;
	

	public Complain() {
	}

	public Complain(String subject,String userId, String complain, String status, String adminMessage,String wlId,String complainType, String date, String time) {
		this.subject = subject;
		this.userId = userId;
		this.complain = complain;
		this.status = status;
		this.adminMessage = adminMessage;
		this.wlId = wlId;
		this.complainType = complainType;
		this.date = date;
		this.time = time;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getComplain() {
		return this.complain;
	}

	public void setComplain(String complain) {
		this.complain = complain;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "admin_message")
	public String getAdminMessage() {
		return this.adminMessage;
	}

	public void setAdminMessage(String adminMessage) {
		this.adminMessage = adminMessage;
	}

	@Column(name = "wl_id")
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}
	
	@Column(name = "complain_type")
	public String getComplainType() {
		return complainType;
	}

	public void setComplainType(String complainType) {
		this.complainType = complainType;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

}
