package com.recharge.model;
// Generated Sep 14, 2017 9:27:29 AM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Defaultcommission generated by hbm2java
 */

@Entity
@Table(name = "defaultcommission")

@NamedQueries({ 
	@NamedQuery(name = "GetDefaultcommissionByOperatorAndUserId", query = "from Defaultcommission As dc where dc.userId = :userId and dc.operatorId = :operatorId"),
})
public class Defaultcommission implements java.io.Serializable {

	private Integer commissionId;
	private String userId;
	private Integer operatorId;
	private Double superDistributor;
	private Double distributor;
	private Double retailer;

	public Defaultcommission() {
	}

	public Defaultcommission(String userId, Integer operatorId, Double superDistributor, Double distributor,
			Double retailer) {
		this.userId = userId;
		this.operatorId = operatorId;
		this.superDistributor = superDistributor;
		this.distributor = distributor;
		this.retailer = retailer;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getCommissionId() {
		return this.commissionId;
	}

	public void setCommissionId(Integer commissionId) {
		this.commissionId = commissionId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	public Double getSuperDistributor() {
		return this.superDistributor;
	}

	public void setSuperDistributor(Double superDistributor) {
		this.superDistributor = superDistributor;
	}

	public Double getDistributor() {
		return this.distributor;
	}

	public void setDistributor(Double distributor) {
		this.distributor = distributor;
	}

	public Double getRetailer() {
		return this.retailer;
	}

	public void setRetailer(Double retailer) {
		this.retailer = retailer;
	}

}
