package com.recharge.model;
// Generated Nov 22, 2017 1:49:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EarningSurcharge generated by hbm2java
 */

@Entity
@Table(name = "earning_surcharge")
public class EarningSurcharge implements java.io.Serializable {
	private Integer id;
	private Integer roleId;
	private String wlId;
	private String userId;
	private Double comm;
	private Double charge;
	private String narration;
	private String date;
	private String time;

	public EarningSurcharge() {
	}

	public EarningSurcharge(Integer roleId, String wlId, String userId, Double comm, Double charge, String narration,
			String date, String time) {
		this.roleId = roleId;
		this.wlId = wlId;
		this.userId = userId;
		this.comm = comm;
		this.charge = charge;
		this.narration = narration;
		this.date = date;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "wl_id")
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Double getComm() {
		return this.comm;
	}

	public void setComm(Double comm) {
		this.comm = comm;
	}

	public Double getCharge() {
		return this.charge;
	}

	public void setCharge(Double charge) {
		this.charge = charge;
	}

	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}
}
