package com.recharge.model;
// Generated Nov 17, 2017 3:09:03 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ifsccode generated by hbm2java
 */

@Entity
@Table(name = "ifsccode")
public class Ifsccode implements java.io.Serializable {

	private Integer id;
	private String bankName;
	private String ifscCode;

	public Ifsccode() {
	}

	public Ifsccode(String bankName, String ifscCode) {
		this.bankName = bankName;
		this.ifscCode = ifscCode;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getIfscCode() {
		return this.ifscCode;
	}

	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}

}
