package com.recharge.model;
// Generated Nov 21, 2017 10:00:15 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Impsverification generated by hbm2java
 */

@Entity
@Table(name = "impsverification")
@NamedQueries({@NamedQuery(name="getImpsverification",query="From Impsverification where userId=:userId")})
public class Impsverification implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String wlId;
	private String roleId;
	private Double verification;

	public Impsverification() {
	}

	public Impsverification(String userId, String wlId, String roleId, Double verification) {
		this.userId = userId;
		this.wlId = wlId;
		this.roleId = roleId;
		this.verification = verification;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "wl_id")
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public Double getVerification() {
		return this.verification;
	}

	public void setVerification(Double verification) {
		this.verification = verification;
	}

}
