package com.recharge.model;
// Generated Nov 21, 2017 10:00:15 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Impscommission generated by hbm2java
 */

@Entity
@Table(name = "impscommission")
@NamedQueries({@NamedQuery(name="getImpsCommissionByUsername",query="From Impscommission where userId=:userId")})
public class Impscommission implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String wlId;
	private String roleId;
	private Double charge;
	private Double slab1;
	private Double slab2;

	public Impscommission() {
	}

	public Impscommission(String userId, String wlId, String roleId, Double charge, Double slab1, Double slab2) {
		this.userId = userId;
		this.wlId = wlId;
		this.roleId = roleId;
		this.charge = charge;
		this.slab1 = slab1;
		this.slab2 = slab2;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "wl_id")
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public Double getCharge() {
		return this.charge;
	}

	public void setCharge(Double charge) {
		this.charge = charge;
	}

	public Double getSlab1() {
		return this.slab1;
	}

	public void setSlab1(Double slab1) {
		this.slab1 = slab1;
	}

	public Double getSlab2() {
		return this.slab2;
	}

	public void setSlab2(Double slab2) {
		this.slab2 = slab2;
	}

}
