package com.recharge.model;
// Generated Aug 31, 2017 9:56:23 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Individualcommission generated by hbm2java
 */

@Entity
@Table(name = "individualcommission")

@NamedQueries({
		@NamedQuery(name = "GetIndividualcommissionByOperatorAndUserId", query = "from Individualcommission As ic where ic.userName = :userId and ic.operatorId = :operatorId"), })
public class Individualcommission implements java.io.Serializable {

	private Integer commissionId;
	private String userName;
	private Integer operatorId;
	private Double commission;

	public Individualcommission() {
	}

	public Individualcommission(String userName, Integer operatorId, Double commission) {
		this.userName = userName;
		this.operatorId = operatorId;
		this.commission = commission;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getCommissionId() {
		return this.commissionId;
	}

	public void setCommissionId(Integer commissionId) {
		this.commissionId = commissionId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	public Double getCommission() {
		return this.commission;
	}

	public void setCommission(Double commission) {
		this.commission = commission;
	}

}
