package com.recharge.model;
// Generated Sep 18, 2017 5:18:21 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Individualcharge generated by hbm2java
 */

@Entity
@Table(name = "individualcharge")
@NamedQueries({ 
	@NamedQuery(name = "GetIndividualchargeByUserIdAndOperatorId", query = "from Individualcharge As ic where ic.userId=:userId and ic.operatorId=:operatorId"),
})
public class Individualcharge implements java.io.Serializable {

	private Integer id;
	private String userId;
	private Double rupees;
	private Double percentage;
	private String flag;
	private String wlId;
	private Integer operatorId;

	public Individualcharge() {
	}

	public Individualcharge(String userId, Double rupees, Double percentage, String flag, String wlId,
			Integer operatorId) {
		this.userId = userId;
		this.rupees = rupees;
		this.percentage = percentage;
		this.flag = flag;
		this.wlId = wlId;
		this.operatorId = operatorId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Double getRupees() {
		return this.rupees;
	}

	public void setRupees(Double rupees) {
		this.rupees = rupees;
	}

	public Double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Double percentage) {
		this.percentage = percentage;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
	@Column(name = "wl_id")
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

	public Integer getOperatorId() {
		return operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

}
