package com.recharge.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

// Generated Nov 14, 2017 9:36:19 AM by Hibernate Tools 4.3.1

/**
 * Insurance generated by hbm2java
 */

@Entity
@Table(name = "insurance")
@NamedQueries({ @NamedQuery(name = "GetInsuranceByIdAndUser", query = "from Insurance As ins where ins.userId =:userId and userId.id = :id"),
	@NamedQuery(name = "GetInsuranceByinsTid", query = "from Insurance As ins where ins.insTid =:insTid"),
})
public class Insurance implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String insTid;
	private String operatorCode;
	private String policyHolderName;
	private String policyNumber;
	private String dob;
	private Double amount;
	private String custMobile;
	private String wlId;
	private String status;	
	private String recieptNumber;
	private String attachedFlag;
	private String submitDate;
	private String submitTime;

	public Insurance() {
	}

	public Insurance(String userId, String insTid, String operatorCode, String policyHolderName, String policyNumber,
			String dob, Double amount, String custMobile, String wlId, String status, String recieptNumber,
			String attachedFlag, String submitDate, String submitTime) {
		this.userId = userId;
		this.insTid = insTid;
		this.operatorCode = operatorCode;
		this.policyHolderName = policyHolderName;
		this.policyNumber = policyNumber;
		this.dob = dob;
		this.amount = amount;
		this.custMobile = custMobile;
		this.wlId = wlId;
		this.status = status;		
		this.recieptNumber = recieptNumber;
		this.attachedFlag = attachedFlag;
		this.submitDate = submitDate;
		this.submitTime = submitTime;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getInsTid() {
		return this.insTid;
	}

	public void setInsTid(String insTid) {
		this.insTid = insTid;
	}

	public String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(String operatorCode) {
		this.operatorCode = operatorCode;
	}
	@Column(name = "policy_holder_name")
	public String getPolicyHolderName() {
		return this.policyHolderName;
	}

	public void setPolicyHolderName(String policyHolderName) {
		this.policyHolderName = policyHolderName;
	}
	@Column(name = "policy_number")
	public String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public String getCustMobile() {
		return this.custMobile;
	}

	public void setCustMobile(String custMobile) {
		this.custMobile = custMobile;
	}
	@Column(name = "wl_id")
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}	

	public String getRecieptNumber() {
		return this.recieptNumber;
	}

	public void setRecieptNumber(String recieptNumber) {
		this.recieptNumber = recieptNumber;
	}

	public String getAttachedFlag() {
		return this.attachedFlag;
	}

	public void setAttachedFlag(String attachedFlag) {
		this.attachedFlag = attachedFlag;
	}

	public String getSubmitDate() {
		return this.submitDate;
	}

	public void setSubmitDate(String submitDate) {
		this.submitDate = submitDate;
	}

	public String getSubmitTime() {
		return this.submitTime;
	}

	public void setSubmitTime(String submitTime) {
		this.submitTime = submitTime;
	}
}
