package com.recharge.model;
// Generated Oct 6, 2017 10:45:57 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * News generated by hbm2java
 */

@Entity
@Table(name = "news")

@NamedQueries({ @NamedQuery(name = "GetNewsByWlId", query = "from News As news where news.wlId=:wlId") })
public class News implements java.io.Serializable {

	private Integer newsid;
	private String news;
	private String wlId;

	public News() {
	}

	public News(String news, String wlId) {
		this.news = news;
		this.wlId = wlId;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getNewsid() {
		return this.newsid;
	}

	public void setNewsid(Integer newsid) {
		this.newsid = newsid;
	}

	public String getNews() {
		return this.news;
	}

	public void setNews(String news) {
		this.news = news;
	}

	@Column(name = "wl_id")
	public String getWlId() {
		return wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

}
