package com.recharge.model;
// Generated Sep 18, 2017 11:27:41 AM by Hibernate Tools 4.3.1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Rechargedetails generated by hbm2java
 */

@Entity
@Table(name = "rechargedetails")

@NamedQueries({ 
	@NamedQuery(name = "GetRechargeDetailsByTid", query = "from Rechargedetails As rd where rd.tid=:tid"),
	@NamedQuery(name = "GetRechargeDetailsByPTid", query = "from Rechargedetails As rd where rd.ptid=:ptid")
})

public class Rechargedetails implements Serializable {

	private Integer id;
	private String userId;
	private String mobile;
	private Integer operatorId;
	private Double openBal;
	private Double amount;
	private Double charge;
	private Double comm;
	private Double closeBal;
	private String tid;
	private String oid;
	private String ptid;
	private String status;
	private String validation;
	private String source;
	private Integer apiId;
	private Integer roleId;
	private String wlId;
	private String date;
	private String time;
	private String ip;
	
	public Rechargedetails() {
	}

	public Rechargedetails(String userId, String mobile, Integer operatorId, Double openBal, Double amount,
			Double charge, Double comm, Double closeBal, String tid, String oid, String ptid, String status,
			String validation, String source, Integer apiId, Integer roleId, String wlId, String date, String time, String ip) {
		this.userId = userId;
		this.mobile = mobile;
		this.operatorId = operatorId;
		this.openBal = openBal;
		this.amount = amount;
		this.charge = charge;
		this.comm = comm;
		this.closeBal = closeBal;
		this.tid = tid;
		this.oid = oid;
		this.ptid = ptid;
		this.status = status;
		this.validation = validation;
		this.source = source;
		this.apiId = apiId;
		this.roleId = roleId;
		this.wlId = wlId;
		this.date = date;
		this.time = time;
		this.ip = ip;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Integer getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	public Double getOpenBal() {
		return this.openBal;
	}

	public void setOpenBal(Double openBal) {
		this.openBal = openBal;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Double getCharge() {
		return this.charge;
	}

	public void setCharge(Double charge) {
		this.charge = charge;
	}

	public Double getComm() {
		return comm;
	}

	public void setComm(Double comm) {
		this.comm = comm;
	}

	public Double getCloseBal() {
		return this.closeBal;
	}

	public void setCloseBal(Double closeBal) {
		this.closeBal = closeBal;
	}

	public String getTid() {
		return this.tid;
	}

	public void setTid(String tid) {
		this.tid = tid;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public String getPtid() {
		return this.ptid;
	}

	public void setPtid(String ptid) {
		this.ptid = ptid;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getValidation() {
		return this.validation;
	}

	public void setValidation(String validation) {
		this.validation = validation;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Integer getApiId() {
		return this.apiId;
	}

	public void setApiId(Integer apiId) {
		this.apiId = apiId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "wl_id")
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}
	
	public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

}
