package com.recharge.model;
// Generated Aug 31, 2017 9:56:23 PM by Hibernate Tools 4.3.1



/**
 * Service generated by hbm2java
 */
public class Service  implements java.io.Serializable {


     private Integer serviceType;
     private String serviceName;

    public Service() {
    }

    public Service(String serviceName) {
       this.serviceName = serviceName;
    }
   
    public Integer getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(Integer serviceType) {
        this.serviceType = serviceType;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }




}


