package com.recharge.model;
// Generated Oct 16, 2017 4:00:44 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Signinhistory generated by hbm2java
 */

@Entity
@Table(name = "signinhistory")

@NamedQueries({ 
	@NamedQuery(name = "GetSigninhistoryDeviceId", query = "from Signinhistory As sh where sh.deviceId=:deviceId"),
	@NamedQuery(name = "GetSigninhistoryByUserIdAndDeviceId", query = "from Signinhistory As sh where sh.deviceId=:deviceId and sh.userId = :userId")
})
public class Signinhistory implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String mobile;
	private String ip;
	private String deviceId;
	private String date;
	private String time;
	

	public Signinhistory() {
	}

	public Signinhistory(String userId, String mobile, String ip, String deviceId, String date, String time) {
		this.userId = userId;
		this.mobile = mobile;
		this.ip = ip;
		this.deviceId = deviceId;
		this.date = date;
		this.time = time;
		
	}	
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

}
