package com.recharge.model;
// Generated Oct 24, 2017 3:51:36 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * SmsCredential generated by hbm2java
 */

@Entity
@Table(name = "sms_credential")

@NamedQueries({ @NamedQuery(name = "GetSmsCredentialByWlId", query = "from SmsCredential As sms where sms.wlId=:wlId") })
public class SmsCredential implements java.io.Serializable {

	private Integer id;
	private String smsUsername;
	private String smsPassword;
	private String senderId;
	private String wlId;
	private String company;
	private String domain;

	public SmsCredential() {
	}

	public SmsCredential(String smsUsername, String smsPassword, String senderId, String wlId,String company,String domain) {
		this.smsUsername = smsUsername;
		this.smsPassword = smsPassword;
		this.senderId = senderId;
		this.wlId = wlId;
		this.company = company;
		this.domain = domain;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSmsUsername() {
		return this.smsUsername;
	}

	public void setSmsUsername(String smsUsername) {
		this.smsUsername = smsUsername;
	}

	public String getSmsPassword() {
		return this.smsPassword;
	}

	public void setSmsPassword(String smsPassword) {
		this.smsPassword = smsPassword;
	}

	public String getSenderId() {
		return this.senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	@Column(name = "wl_id")
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	
}
