package com.recharge.model;
// Generated Aug 31, 2017 9:56:23 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Transactiondetails generated by hbm2java
 */

@Entity
@Table(name = "transactiondetails")

@NamedQueries({ 
	@NamedQuery(name = "getTransactionReportForAll", query = "from Transactiondetails As transaction where transaction.wlId = :wlId and transaction.date between :startDate and :endDate order by id desc"),
	@NamedQuery(name = "getTransactionReportForUser", query = "from Transactiondetails As transaction where transaction.userId = :userId and transaction.wlId = :wlId and transaction.date between :startDate and :endDate order by id desc"),
})
public class Transactiondetails implements java.io.Serializable {

	private Integer transId;
	private String userId;
	private Double openingBal;
	private Double credit;
	private Double debit;
	private Double closingBal;
	private String narration;
	private String remarks;
	private String date;
	private String time;
	private Double adopbal;
	private Double adclbal;
	private String wlId;
	
	public Transactiondetails() {
	}

	public Transactiondetails(String userId, Double openingBal, Double credit, Double debit, Double closingBal,
			String narration, String remarks, String date, String time,Double adopbal,Double adclbal, String wlId) {
		this.userId = userId;
		this.openingBal = openingBal;
		this.credit = credit;
		this.debit = debit;
		this.closingBal = closingBal;
		this.narration = narration;
		this.remarks = remarks;
		this.date = date;
		this.time = time;
		this.setAdopbal(adopbal);
		this.setAdclbal(adclbal);
		this.wlId = wlId;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getTransId() {
		return this.transId;
	}

	public void setTransId(Integer transId) {
		this.transId = transId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Double getOpeningBal() {
		return this.openingBal;
	}

	public void setOpeningBal(Double openingBal) {
		this.openingBal = openingBal;
	}

	public Double getCredit() {
		return this.credit;
	}

	public void setCredit(Double credit) {
		this.credit = credit;
	}

	public Double getDebit() {
		return this.debit;
	}

	public void setDebit(Double debit) {
		this.debit = debit;
	}

	public Double getClosingBal() {
		return this.closingBal;
	}

	public void setClosingBal(Double closingBal) {
		this.closingBal = closingBal;
	}

	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}
	
	public Double getAdopbal() {
		return adopbal;
	}

	public void setAdopbal(Double adopbal) {
		this.adopbal = adopbal;
	}

	public Double getAdclbal() {
		return adclbal;
	}

	public void setAdclbal(Double adclbal) {
		this.adclbal = adclbal;
	}

	@Column(name = "wl_id")
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

}
