package com.recharge.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

// Generated Mar 12, 2017 8:59:20 PM by Hibernate Tools 4.3.1

/**
 * User generated by hbm2java
 */

@Entity
@Table(name = "user")

@NamedQueries({ @NamedQuery(name = "GetUserByUserId", query = "from User As user where user.userId=:userId"),
	@NamedQuery(name = "getUserByMobile", query = "from User As user where user.mobile = :mobile"),
	@NamedQuery(name = "getResellerByAdmin", query = "from User As user where  user.roleId = 2 and user.delFlag = '0'"),
		@NamedQuery(name = "getResellerDetails", query = "from User As user where user.wlId=:wlId and (user.roleId = 1 or user.roleId = 2)"),
		@NamedQuery(name = "GetAllUserByAdmin", query = "from User As user where user.userId != 'admin' and user.roleId != 2 and user.delFlag = '0' order by createdDate"),
		@NamedQuery(name = "GetAllUserByReseller", query = "from User As user where user.roleId != 2 and user.wlId=:wlId and user.delFlag = '0' order by user.createdDate"),
		@NamedQuery(name = "GetUserByUserIdAndWlId", query = "from User As user where user.userId=:userId and user.wlId=:wlId and user.delFlag = '0'"),
		@NamedQuery(name = "getUserByAdminType", query = "from User As user where user.roleId = :userTyPe and user.wlId=:wiId and  delFlag='0'"),
		@NamedQuery(name = "GetUserByUplineId", query = "from User As user where user.uplineId=:uplineId and user.delFlag = '0'"),
		@NamedQuery(name = "GetUserByRoleId", query = "from User As user where user.roleId=:roleId and user.delFlag = '0' order by user.name"),
		@NamedQuery(name = "GetUserByRoleIdAndWlId", query = "from User As user where user.roleId=:roleId and user.wlId=:wlId and user.delFlag = '0' order by user.name"),
		@NamedQuery(name = "GetUserByWlId", query = "from User As user where user.wlId=:wlId and user.delFlag = '0'"),
		@NamedQuery(name = "GetAllUser", query = "from User As user where user.delFlag = '0' and user.userId!='admin'"),
		@NamedQuery(name = "GetUserByUplineIdAndWlId", query = "from User As user where user.wlId=:wlId and user.uplineId=:uplineId and user.delFlag = '0' order by user.name"),
		@NamedQuery(name = "GetUserByRoleIdUserIdAndWlId", query = "from User As user where user.wlId=:wlId and user.userId=:userId and user.roleId=:roleId and user.delFlag = '0'"),
		@NamedQuery(name = "GetUserByRoleIdUplineIdAndWlId", query = "from User As user where user.wlId=:wlId and user.uplineId=:uplineId and user.roleId=:roleId and user.delFlag = '0' order by user.name"),		
		@NamedQuery(name = "advancedSearchUserByAdmin", query = "from User As user where (user.mobile = :mobile or user.email = :mobile or user.name = :mobile) and user.roleId != 1 and user.delFlag = '0'"),
		@NamedQuery(name = "advancedSearchUserByUser", query = "from User As user where (user.mobile = :mobile or user.email = :mobile or user.name = :mobile) and (user.uplineId = :uplineId or user.uplineId in (select userId from user as u1 where u1.uplineId = :uplineId)) and user.roleId != 1 and user.delFlag = '0'"),
		@NamedQuery(name = "getMyRetailerForSD", query = "from User as user where user.uplineId in (select userId from user as u1 where u1.uplineId = :userId)"),
		@NamedQuery(name = "getUserByUserType", query = "from User As user where user.roleId = :userTyPe and  user.uplineId=:uplineid and  delFlag='0'"),
		@NamedQuery(name = "getMyUserForSD", query = "from User as user where user.uplineId = :userId or user.uplineId in (select userId from user as u1 where u1.uplineId = :userId) order by createdDate desc")

})
public class User implements java.io.Serializable {

	private String userId;
	private String password;
	private Integer roleId;
	private String wlId;
	private String userName;
	private String name;
	private String firmName;
	private String address;
	private String city;
	private String pinCode;
	private String state;
	private String country;
	private String mobile;
	private String uplineId;
	private String email;
	private String createdDate;
	private String createdTime;
	private Double balance;
	private String status;
	private String delFlag;
	private String tranPin;
	private double lockedAmount;

	public User() {
	}

	public User(String userId) {
		this.userId = userId;
	}

	public User(String userId, String password, Integer roleId, String wlId, String userName, String name,
			String firmName, String address, String city, String pinCode, String state, String country, String mobile,
			String uplineId, String email, String createdDate, String createdTime, Double balance, String status,
			String delFlag, String tranPin, double lockedAmount) {
		this.userId = userId;
		this.password = password;
		this.roleId = roleId;
		this.wlId = wlId;
		this.userName = userName;
		this.name = name;
		this.firmName = firmName;
		this.address = address;
		this.city = city;
		this.pinCode = pinCode;
		this.state = state;
		this.country = country;
		this.mobile = mobile;
		this.uplineId = uplineId;
		this.email = email;
		this.createdDate = createdDate;
		this.createdTime = createdTime;
		this.balance = balance;
		this.status = status;
		this.delFlag = delFlag;
		this.tranPin = tranPin;
		this.lockedAmount = lockedAmount;
	}

	@Id
	@Column(name = "userId", unique = true, nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "wl_id")
	public String getWlId() {
		return wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFirmName() {
		return firmName;
	}

	public void setFirmName(String firmName) {
		this.firmName = firmName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getUplineId() {
		return this.uplineId;
	}

	public void setUplineId(String uplineId) {
		this.uplineId = uplineId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(String createdTime) {
		this.createdTime = createdTime;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTranPin() {
		return tranPin;
	}

	public void setTranPin(String tranPin) {
		this.tranPin = tranPin;
	}

	public double getLockedAmount() {
		return lockedAmount;
	}

	public void setLockedAmount(double lockedAmount) {
		this.lockedAmount = lockedAmount;
	}

}
