
package com.skypoint.moneyapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MoneyApi", targetNamespace = "http://moneyapi.skypoint.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MoneyApi {


    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetKYCStatusAndLimitResponse
     * @throws MyServiceException
     */
    @WebMethod(action = "getKYCStatusAndLimit")
    @WebResult(name = "getKYCStatusAndLimitResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "getKYCStatusAndLimit", output = "http://moneyapi.skypoint.com/MoneyApi/getKYCStatusAndLimitResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/getKYCStatusAndLimit/Fault/MyServiceException")
    })
    public GetKYCStatusAndLimitResponse getKYCStatusAndLimit(
        @WebParam(name = "getKYCStatusAndLimit", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetKYCStatusAndLimit parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.ResetConsumerIpinResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "ResetConsumerIpin", action = "ResetConsumerIpin")
    @WebResult(name = "ResetConsumerIpinResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "ResetConsumerIpin", output = "http://moneyapi.skypoint.com/MoneyApi/ResetConsumerIpinResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/ResetConsumerIpin/Fault/MyServiceException")
    })
    public ResetConsumerIpinResponse resetConsumerIpin(
        @WebParam(name = "ResetConsumerIpin", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        ResetConsumerIpin parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.CheckTransactionStatusResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "CheckTransactionStatus", action = "CheckTransactionStatus")
    @WebResult(name = "CheckTransactionStatusResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "CheckTransactionStatus", output = "http://moneyapi.skypoint.com/MoneyApi/CheckTransactionStatusResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/CheckTransactionStatus/Fault/MyServiceException")
    })
    public CheckTransactionStatusResponse checkTransactionStatus(
        @WebParam(name = "CheckTransactionStatus", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        CheckTransactionStatus parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetIFSCBankResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "GetIFSCBank", action = "GetIFSCBank")
    @WebResult(name = "GetIFSCBankResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "GetIFSCBank", output = "http://moneyapi.skypoint.com/MoneyApi/GetIFSCBankResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/GetIFSCBank/Fault/MyServiceException")
    })
    public GetIFSCBankResponse getIFSCBank(
        @WebParam(name = "GetIFSCBank", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetIFSCBank parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetIFSCStatesResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "GetIFSCStates", action = "GetIFSCStates")
    @WebResult(name = "GetIFSCStatesResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "GetIFSCStates", output = "http://moneyapi.skypoint.com/MoneyApi/GetIFSCStatesResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/GetIFSCStates/Fault/MyServiceException")
    })
    public GetIFSCStatesResponse getIFSCStates(
        @WebParam(name = "GetIFSCStates", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetIFSCStates parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetIFSCCityResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "GetIFSCCity", action = "GetIFSCCity")
    @WebResult(name = "GetIFSCCityResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "GetIFSCCity", output = "http://moneyapi.skypoint.com/MoneyApi/GetIFSCCityResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/GetIFSCCity/Fault/MyServiceException")
    })
    public GetIFSCCityResponse getIFSCCity(
        @WebParam(name = "GetIFSCCity", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetIFSCCity parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetIFSCBranchResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "GetIFSCBranch", action = "GetIFSCBranch")
    @WebResult(name = "GetIFSCBranchResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "GetIFSCBranch", output = "http://moneyapi.skypoint.com/MoneyApi/GetIFSCBranchResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/GetIFSCBranch/Fault/MyServiceException")
    })
    public GetIFSCBranchResponse getIFSCBranch(
        @WebParam(name = "GetIFSCBranch", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetIFSCBranch parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetCustomerStatusResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "GetCustomerStatus", action = "GetCustomerStatus")
    @WebResult(name = "GetCustomerStatusResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "GetCustomerStatus", output = "http://moneyapi.skypoint.com/MoneyApi/GetCustomerStatusResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/GetCustomerStatus/Fault/MyServiceException")
    })
    public GetCustomerStatusResponse getCustomerStatus(
        @WebParam(name = "GetCustomerStatus", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetCustomerStatus parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.RegisterCustomerResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "RegisterCustomer", action = "RegisterCustomer")
    @WebResult(name = "RegisterCustomerResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "RegisterCustomer", output = "http://moneyapi.skypoint.com/MoneyApi/RegisterCustomerResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/RegisterCustomer/Fault/MyServiceException")
    })
    public RegisterCustomerResponse registerCustomer(
        @WebParam(name = "RegisterCustomer", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        RegisterCustomer parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.RegisterBeneficiaryResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "RegisterBeneficiary", action = "RegisterBeneficiary")
    @WebResult(name = "RegisterBeneficiaryResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "RegisterBeneficiary", output = "http://moneyapi.skypoint.com/MoneyApi/RegisterBeneficiaryResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/RegisterBeneficiary/Fault/MyServiceException")
    })
    public RegisterBeneficiaryResponse registerBeneficiary(
        @WebParam(name = "RegisterBeneficiary", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        RegisterBeneficiary parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetBeneficiaryDetailsResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "GetBeneficiaryDetails", action = "GetBeneficiaryDetails")
    @WebResult(name = "GetBeneficiaryDetailsResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "GetBeneficiaryDetails", output = "http://moneyapi.skypoint.com/MoneyApi/GetBeneficiaryDetailsResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/GetBeneficiaryDetails/Fault/MyServiceException")
    })
    public GetBeneficiaryDetailsResponse getBeneficiaryDetails(
        @WebParam(name = "GetBeneficiaryDetails", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetBeneficiaryDetails parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetBeneficiaryStatusResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "GetBeneficiaryStatus", action = "GetBeneficiaryStatus")
    @WebResult(name = "GetBeneficiaryStatusResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "GetBeneficiaryStatus", output = "http://moneyapi.skypoint.com/MoneyApi/GetBeneficiaryStatusResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/GetBeneficiaryStatus/Fault/MyServiceException")
    })
    public GetBeneficiaryStatusResponse getBeneficiaryStatus(
        @WebParam(name = "GetBeneficiaryStatus", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetBeneficiaryStatus parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.SubmitPaymentDetailsResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "SubmitPaymentDetails", action = "SubmitPaymentDetails")
    @WebResult(name = "SubmitPaymentDetailsResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "SubmitPaymentDetails", output = "http://moneyapi.skypoint.com/MoneyApi/SubmitPaymentDetailsResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/SubmitPaymentDetails/Fault/MyServiceException")
    })
    public SubmitPaymentDetailsResponse submitPaymentDetails(
        @WebParam(name = "SubmitPaymentDetails", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        SubmitPaymentDetails parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.ConfirmPaymentDetailsResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "ConfirmPaymentDetails", action = "ConfirmPaymentDetails")
    @WebResult(name = "ConfirmPaymentDetailsResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "ConfirmPaymentDetails", output = "http://moneyapi.skypoint.com/MoneyApi/ConfirmPaymentDetailsResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/ConfirmPaymentDetails/Fault/MyServiceException")
    })
    public ConfirmPaymentDetailsResponse confirmPaymentDetails(
        @WebParam(name = "ConfirmPaymentDetails", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        ConfirmPaymentDetails parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.SetBeneficiaryAsVerfiedResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "SetBeneficiaryAsVerfied", action = "SetBeneficiaryAsVerfied")
    @WebResult(name = "SetBeneficiaryAsVerfiedResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "SetBeneficiaryAsVerfied", output = "http://moneyapi.skypoint.com/MoneyApi/SetBeneficiaryAsVerfiedResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/SetBeneficiaryAsVerfied/Fault/MyServiceException")
    })
    public SetBeneficiaryAsVerfiedResponse setBeneficiaryAsVerfied(
        @WebParam(name = "SetBeneficiaryAsVerfied", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        SetBeneficiaryAsVerfied parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.ResendOTPResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "ResendOTP", action = "ResendOTP")
    @WebResult(name = "ResendOTPResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "ResendOTP", output = "http://moneyapi.skypoint.com/MoneyApi/ResendOTPResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/ResendOTP/Fault/MyServiceException")
    })
    public ResendOTPResponse resendOTP(
        @WebParam(name = "ResendOTP", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        ResendOTP parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetTransactionStatusResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "GetTransactionStatus", action = "GetTransactionStatus")
    @WebResult(name = "GetTransactionStatusResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "GetTransactionStatus", output = "http://moneyapi.skypoint.com/MoneyApi/GetTransactionStatusResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/GetTransactionStatus/Fault/MyServiceException")
    })
    public GetTransactionStatusResponse getTransactionStatus(
        @WebParam(name = "GetTransactionStatus", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetTransactionStatus parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.SubmitPaymentIPINResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "SubmitPaymentIPIN", action = "SubmitPaymentIPIN")
    @WebResult(name = "SubmitPaymentIPINResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "SubmitPaymentIPIN", output = "http://moneyapi.skypoint.com/MoneyApi/SubmitPaymentIPINResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/SubmitPaymentIPIN/Fault/MyServiceException")
    })
    public SubmitPaymentIPINResponse submitPaymentIPIN(
        @WebParam(name = "SubmitPaymentIPIN", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        SubmitPaymentIPIN parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetConsumerDetailsByConsumerIDResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "GetConsumerDetailsByConsumerID", action = "GetConsumerDetailsByConsumerID")
    @WebResult(name = "GetConsumerDetailsByConsumerIDResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "GetConsumerDetailsByConsumerID", output = "http://moneyapi.skypoint.com/MoneyApi/GetConsumerDetailsByConsumerIDResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/GetConsumerDetailsByConsumerID/Fault/MyServiceException")
    })
    public GetConsumerDetailsByConsumerIDResponse getConsumerDetailsByConsumerID(
        @WebParam(name = "GetConsumerDetailsByConsumerID", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetConsumerDetailsByConsumerID parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.GetIFSCCodeDetailsResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "GetIFSCCodeDetails", action = "GetIFSCCodeDetails")
    @WebResult(name = "GetIFSCCodeDetailsResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "GetIFSCCodeDetails", output = "http://moneyapi.skypoint.com/MoneyApi/GetIFSCCodeDetailsResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/GetIFSCCodeDetails/Fault/MyServiceException")
    })
    public GetIFSCCodeDetailsResponse getIFSCCodeDetails(
        @WebParam(name = "GetIFSCCodeDetails", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        GetIFSCCodeDetails parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.UpdateBeneficiaryNameByBeneficiaryIDResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "UpdateBeneficiaryNameByBeneficiaryID", action = "UpdateBeneficiaryNameByBeneficiaryID")
    @WebResult(name = "UpdateBeneficiaryNameByBeneficiaryIDResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "UpdateBeneficiaryNameByBeneficiaryID", output = "http://moneyapi.skypoint.com/MoneyApi/UpdateBeneficiaryNameByBeneficiaryIDResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/UpdateBeneficiaryNameByBeneficiaryID/Fault/MyServiceException")
    })
    public UpdateBeneficiaryNameByBeneficiaryIDResponse updateBeneficiaryNameByBeneficiaryID(
        @WebParam(name = "UpdateBeneficiaryNameByBeneficiaryID", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        UpdateBeneficiaryNameByBeneficiaryID parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.skypoint.moneyapi.BeneficiaryListResponse
     * @throws MyServiceException
     */
    @WebMethod(operationName = "BeneficiaryList", action = "BeneficiaryList")
    @WebResult(name = "BeneficiaryListResponse", targetNamespace = "http://moneyapi.skypoint.com/", partName = "result")
    @Action(input = "BeneficiaryList", output = "http://moneyapi.skypoint.com/MoneyApi/BeneficiaryListResponse", fault = {
        @FaultAction(className = MyServiceException.class, value = "http://moneyapi.skypoint.com/MoneyApi/BeneficiaryList/Fault/MyServiceException")
    })
    public BeneficiaryListResponse beneficiaryList(
        @WebParam(name = "BeneficiaryList", targetNamespace = "http://moneyapi.skypoint.com/", partName = "parameters")
        BeneficiaryList parameters,
        @WebParam(name = "Authentication", targetNamespace = "http://moneyapi.skypoint.com/", header = true, partName = "Authentication")
        Authentication authentication)
        throws MyServiceException
    ;

}
