
package com.skypoint.moneyapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MyServiceFault", targetNamespace = "http://moneyapi.skypoint.com/")
public class MyServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MyServiceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MyServiceException(String message, MyServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MyServiceException(String message, MyServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.skypoint.moneyapi.MyServiceFault
     */
    public MyServiceFault getFaultInfo() {
        return faultInfo;
    }

}
